"""Export the condition registry to `contracts/conditions.json`.

**Why an exported file at all, when the registry is the single list.** SPEC-009
needs the *set of codes* to assert that every condition it can receive has a
rendering — coverage in both directions, the client half of SPEC-006 AC-17. That
set is not in `openapi.json`: the published schema carries the enum members of
`presentation` and `reset`, not the codes. A TypeScript test cannot import a
Python dict, so something has to cross the language boundary.

**The danger this file creates, and how it is contained.** A checked-in copy of
the taxonomy living outside the registry is exactly what the runtime design
refuses, relocated into the build. Left as a hand-updated fixture it would drift
in the familiar direction: someone adds a condition, the frontend's coverage test
enumerates the stale list, the new condition is never rendered, and nothing is
red. So this file is **generated, never edited**, and
`tests/test_api_conditions.py` regenerates it in memory and fails on any
difference — which makes a drifted export a failing build rather than a missing
frontend branch.

    uv run python -m scripts.export_conditions        # rewrite the export

The export is deliberately *not* served by the API. It is a build-time artifact
for a repo-local consumer; publishing the whole taxonomy on the wire would invite
a client to switch on `code`, which Key decision 1 of SPEC-009 forbids.
"""

import json
from pathlib import Path
from typing import Any

from rag_qa.api.conditions import CONDITIONS

REPO_ROOT = Path(__file__).resolve().parent.parent
EXPORT_PATH = REPO_ROOT / "contracts" / "conditions.json"

HEADER = (
    "GENERATED by scripts/export_conditions.py from rag_qa.api.conditions.CONDITIONS. "
    "Do not edit: tests/test_api_conditions.py regenerates this and fails on any diff."
)


def export() -> dict[str, Any]:
    """The registry as data, in a shape a non-Python consumer can read."""
    return {
        "_generated_by": HEADER,
        "conditions": {
            code: {
                "status": spec.status,
                "presentation": str(spec.presentation),
                "reset": str(spec.reset),
                "refusal": spec.refusal,
            }
            # Sorted so the file is stable under dict-insertion changes: a
            # reordered registry must not produce a diff, or the guard test
            # becomes noise and gets regenerated without being read.
            for code, spec in sorted(CONDITIONS.items())
        },
    }


def render() -> str:
    return json.dumps(export(), indent=2, sort_keys=False) + "\n"


def main() -> None:
    EXPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    EXPORT_PATH.write_text(render())
    print(f"wrote {EXPORT_PATH.relative_to(REPO_ROOT)} ({len(export()['conditions'])} conditions)")


if __name__ == "__main__":
    main()
